analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    maintainability-index: 50
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  extends:
    - package:dart_code_metrics_presets/all.yaml